# Generated by Django 5.1.3 on 2024-12-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bug_expected_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('critical', 'Critical')], default='low', max_length=10),
        ),
    ]
