# Generated by Django 5.1.3 on 2024-12-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bounty_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='title',
        ),
        migrations.AlterField(
            model_name='bug',
            name='guide',
            field=models.TextField(blank=True, null=True),
        ),
    ]
