# Generated by Django 5.1.3 on 2024-12-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_bug_description_remove_bug_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Accepted', 'accepted'), ('Rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
