# Generated by Django 5.1.3 on 2024-12-11 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bug_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='step_to_reproduce',
        ),
        migrations.AddField(
            model_name='rewardtransaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewardtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rewardtransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
