# Generated by Django 5.1.3 on 2024-12-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_bounty_step_to_reproduce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
